### ISSUE TITLE
Pretrain weights?

### ISSUE THREAD

**Issue by Boltzmachine** [PhyScene/PhyScene#1]
Correct me if I miss something. How to run the evaluation without the pretrained weights, or without the training script?

**Comment by YandanYang** [comment]
Thanks for pointing out this.
We have uploaded pretrained weight as well as preprocessed dataset just now.

**Comment by Boltzmachine** [comment]
Thank you so much! When will the training scripts be available btw

**Comment by YandanYang** [comment]
The release time is to be determined, since the training code is going through the internal code review. 
We have released the code for the model structure and other algorithmns. You may take it as a reference.

**Comment by Boltzmachine** [comment]
Thanks. Do you have pretrained weights for bedroom?

**Comment by Boltzmachine** [comment]
Also, is the weight for  floor-conditional generation or unconditional generation?

**Comment by skf-1999** [comment]
Will the pre-training model of dining room and bedroom be open source?

**Comment by YandanYang** [comment]
> Also, is the weight for floor-conditional generation or unconditional generation?

The weight is for floor-conditional generation.

**Comment by YandanYang** [comment]
Yes, we will upload the weight for dining room and bedroom later.

**Comment by Jayant1Varma** [comment]
Hi, I can't get the weights because the link on the READ.ME goes to a 404 error page.

**Comment by YandanYang** [comment]
> Hi, I can't get the weights because the link on the READ.ME goes to a 404 error page.

Hi, we have updated the link just now.
