### ISSUE TITLE
GAPartNet数据集报错

### ISSUE THREAD

**Issue by Juno-cyber** [PhyScene/PhyScene#19]
hello，when i am run 
` sh run/test_livingroom_gen_image.sh exp_dir`
and then get 
`FileNotFoundError: [Errno 2] No such file or directory: '/home/yandan/workspace/GAPartNet/dataset/render_tools/meta/partnet_all_id_list.txt'`
i didnt find the GAPartNet dataset, and can not solve this issue.

**Comment by YandanYang** [comment]
Hi,
This file can be found [here](https://github.com/PKU-EPIC/GAPartNet/blob/release/dataset/render_tools/meta/partnet_all_id_list.txt).

**Comment by Juno-cyber** [comment]
Thank you so much. I searched for this project earlier but overlooked it.

**Comment by Juno-cyber** [comment]
Thank you so much. I searched for this project earlier but overlooked it.
