### ISSUE TITLE
Remesh model?

### ISSUE THREAD

**Issue by Boltzmachine** [PhyScene/PhyScene#3]
I saw the code uses remeshed model `remesh_model_path` when generating renderables. However, I did not find how to get the remeshed models.

**Comment by YandanYang** [comment]
The remeshed model of  GAPartNat has already been included in the uploaded dataset. As for 3D FUTURE, we will update it later (Hopefully next week).

**Comment by YandanYang** [comment]
We have uploaded remeshed CAD model of 3D FUTURE [here](https://huggingface.co/datasets/yangyandan/PhyScene/tree/main/dataset).

**Comment by Boltzmachine** [comment]
Thanks!
