### ISSUE TITLE
where is Scene-Diffuser-New

### ISSUE THREAD

**Issue by gyula-coder** [PhyScene/PhyScene#6]
when I run `sh run/pickle_pcd.sh data/pickled_data` to pickle gapartnet, Scene-Diffuser-New in workspace is needed. there is a repository Scene-Diffuser in github but  no directory structure like `Scene-Diffuser-New/data/GPN_open_ratio.json`.

**Comment by YandanYang** [comment]
Thanks for pointing this out.  We have modified the path in the latest commit. 
Note that `GPN_open_ratio.json` is generated in the given code and is no longer used in our solution, 
so we also comment out the corresponding code in this commit.
