### ISSUE TITLE
How to Use Unseen Floorplan in PhyScene?

### ISSUE THREAD

**Issue by foojayyy** [PhyScene/PhyScene#7]
Hello,

I am interested in using PhyScene with previously unseen floor plans. Could you please provide guidance on the necessary parameters and steps needed to achieve this?

Specifically, I would like to know:

What format should the floor plan images be in (e.g., JPEG, PNG)?
Are there any specific preprocessing steps required for these images?
What additional data is required to use a new floor plan effectively in the PhyScene framework?

Thank you for your assistance!

**Comment by YandanYang** [comment]
For unseen floor plan, we do not specifically modify the guidance parameters and steps. You can take the given parameters in the code for reference.

As for the data format of unseen floor plan:
First, you need to prepare a mesh (such as an .obj file) of the floor plan. 
And then the preprocess step `python scripts/preprocess/preprocess_data_prothor.py` will convert the floor plan into a **2D room mask** (both jpeg and png are ok) and record the **center coordinate** of the floor plan. 
The center coordinate is for two purposes: 1) The model takes (x,y)=(0,0) as the center of the floor plan by default, so we need to move the unseen floor plan to (0,0) to fit the model. 2) After genration, you need to move the scene layout back to the original position of the floor plan with the center coordinate.
