### ISSUE TITLE
How to get right_direction_close.obj in GAPartNet?

### ISSUE THREAD

**Issue by Au233** [PhyScene/PhyScene#9]
Hello, your work is very interesting. While reproducing it, I found that the textured_objs folder under each asset in GAPartNet does not contain the right_direction_close.obj file. Could you please let me know how to obtain it?

**Comment by YandanYang** [comment]
Hi, we update the dataset.
You can refer to [this link](https://huggingface.co/datasets/yangyandan/GAPartNet_PhyScene) for full version of preprocessed GAPartNet.
